security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    providers:
        utilisateur_provider:
            entity:
                class: App\Entity\Utilisateur
                property: matricule

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: utilisateur_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_accueil
            

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/manager, roles: ROLE_MANAGER }
        - { path: ^/collaborateur, roles: ROLE_COLLABORATEUR }
        - { path: ^/, roles: PUBLIC_ACCESS }
